services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  api:
    build:
      context: .
      args:
        HTTP_PROXY: http://10.2.68.81:3389/
        HTTPS_PROXY: http://10.2.68.81:3389/
        NO_PROXY: localhost,127.0.0.1,127.0.0.0/8,::1,10.0.0.0/8,qdrant,api
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - qdrant
    volumes:
      - ./data:/app/data
      - ./app:/app/app
      - ./scripts:/app/scripts
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
volumes:
  qdrant_data: